apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-ctse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assignment-ctse
  template:
    metadata:
      labels:
        app: assignment-ctse
    spec:
      containers:
      - name: node-server
        image: it19098838/assignment-ctse:latest
        ports:
        - containerPort: 8081
